name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build & Publish
      uses: Amadevus/pwsh-script@v2
      id: publish-script
      with:
        script: |
          $gitversion = dotnet-gitversion | ConvertFrom-Json 
          setversion $gitversion.AssemblySemVer
          dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true "subcheck.csproj" 
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Executable
        path: ${{ github.workspace }}/bin/Release/net6.0/win-x64/publish/SubCheck.exe

