name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '[17.2,17.3)'
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
    - name: Build & Publish
      run: ./build.ps1
      shell: pwsh  
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Executable
        path: ${{ github.workspace }}/SubCheck.exe

